# Generated by Django 4.1.4 on 2023-03-29 20:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlists",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Playlist_id", models.CharField(max_length=50)),
                ("Playlist_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="room",
            name="code",
            field=models.CharField(
                default=api.models.generate_unique_code, max_length=8, unique=True
            ),
        ),
    ]
